- hosts: "k8s-local"
  strategy: free 
  gather_facts: false
  become: true
  vars: 
  tasks:
  - name: Execute shell commands
    shell: |
      sudo apt install glances -y
  - name: Print
    debug: var=systemctl