- hosts: "k8s-local"
  strategy: free 
  gather_facts: false
  become: true
  vars: 
  tasks:
  - name: Execute shell commands
    shell: |
      sudo swapoff -a
      sudo apt update && sudo apt upgrade -y
  - name: Print
    debug: var=systemctl