- hosts: api_maya
  strategy: free 
  gather_facts: true
  become: false
  vars: 
  tasks:
  - name: Execute shell commands
    shell: |
      cd /var/www/html/api_maya
      php artisan config:clear
      php artisan cache:clear
      sudo systemctl restart php7.1-fpm
  - name: Print
    debug: var=systemctl