- hosts: "loadtesting-servers"
  strategy: free 
  gather_facts: false
  become: false
  vars: 
  tasks:
  - name: Execute shell commands
    shell: |
      sudo yum install glances -y
  - name: Print
    debug: var=systemctl