- name: Check Disk Space and Notify
  hosts: johukum
  gather_facts: true

  tasks:
      - name: Disk usage from command module
        command: df -h
        register: space
      - debug:
              var: space.stdout_lines