- hosts: "loadtesting-servers"
  gather_facts: yes
  become: no
  tasks:
  - name: Copy files from template directory
    copy: 
      src: /home/hose2406101844a/Desktop/trash/grafana/node-exporter
      dest: /home/hose2406101844a