- hosts: "experiment-server"
  gather_facts: yes
  become: no
  connection: ssh
  tasks:
  - name: Copy private key
    copy: 
      src: ../keys/id_rsa
      dest: /home/ubuntu/.ssh/id_rsa
  - name: Copy public key
    copy: 
      src: ../keys/id_rsa.pub
      dest: /home/ubuntu/.ssh/id_rsa.pub