- hosts: jo-services
  strategy: free 
  gather_facts: true
  become: yes
  become_user: ubuntu
  vars: 
  tasks:
  - name: Execute shell commands for jocial-backend
    shell: |
      cd jocial-backend
      git fetch
      git pull
      npm i
  - name: Execute shell commands for jocial-backend
    shell: |
      cd jo-news-backend
      git fetch
      git pull   
      npm i
  - name: Install PM2
    shell: |
      npm i pm2 -g 
  - name: Print
    debug: var=systemctl
